package Ontologia.impl;

import Ontologia.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultCadela <br>
 * @version generated on Tue Oct 19 23:53:40 BRST 2021 by ldrpontes
 */
public class DefaultCadela extends WrappedIndividualImpl implements Cadela {

    public DefaultCadela(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
