package Ontologia;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Tue Oct 19 23:53:40 BRST 2021 by ldrpontes
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#Animal
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANIMAL.<p>
     * 
     */
    public static final OWLClass CLASS_ANIMAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#Animal"));

    /* ***************************************************
     * Class http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#Cadela
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CADELA.<p>
     * 
     */
    public static final OWLClass CLASS_CADELA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#Cadela"));

    /* ***************************************************
     * Class http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#Cao
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAO.<p>
     * 
     */
    public static final OWLClass CLASS_CAO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#Cao"));

    /* ***************************************************
     * Class http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#CaoDomestico
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAODOMESTICO.<p>
     * 
     */
    public static final OWLClass CLASS_CAODOMESTICO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#CaoDomestico"));

    /* ***************************************************
     * Class http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#CaoLobo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAOLOBO.<p>
     * 
     */
    public static final OWLClass CLASS_CAOLOBO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#CaoLobo"));

    /* ***************************************************
     * Class http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#HomoSapiens
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HOMOSAPIENS.<p>
     * 
     */
    public static final OWLClass CLASS_HOMOSAPIENS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#HomoSapiens"));

    /* ***************************************************
     * Class http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#Loba
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOBA.<p>
     * 
     */
    public static final OWLClass CLASS_LOBA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#Loba"));

    /* ***************************************************
     * Class http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#Lobo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOBO.<p>
     * 
     */
    public static final OWLClass CLASS_LOBO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/ldrpontes/ontologies/2021/9/untitled-ontology-2#Lobo"));


}
